### ISSUE TITLE
JADESView_webget needs https

### ISSUE THREAD

**Issue by eclake** [kevinhainline/JADESView#2]
Hi @kevinhainline - thank you so much for putting together the webget version!  Just a note to say that the info in your README file suggests it's sufficient to give http://path/to/files/on/fenrir but that didn't work for me - did work with https://path/to/files/on/fenrir though!

**Comment by kevinhainline** [comment]
I've gone and updated the README to reflect this! Thanks for pointing it out. Hopefully the code doesn't run too slow with these huge mosaics.
