### ISSUE TITLE
Problem with the comments

### ISSUE THREAD

**Issue by eclake** [kevinhainline/JADESView#3]
The output ID in the object notes file doesn't correspond to the actual object ID :-S

I'll look into it and see if I can find the issue today - then re-do my visual inspection :-(

**Comment by kevinhainline** [comment]
Oh no! Can you give me more information about what happened? Can you drop some of the output file text here so that I can see? I am sorry you have to redo your visual inspection! I'm going to see about writing more out to the screen so that you can at least have a secondary record.

**Comment by eclake** [comment]
It's not a problem to re-do the visual inspection, I've not started on the bigger classes yet.  I started to write the ID I see on the screen so that's probably the best thing for me to post for you 
[Object_Notes_class3.txt](https://github.com/kevinhainline/JADESView/files/5843898/Object_Notes_class3.txt)
[class3_ids.list.zip](https://github.com/kevinhainline/JADESView/files/5843902/class3_ids.list.zip)
[JADESView_input_file.dat.zip](https://github.com/kevinhainline/JADESView/files/5843905/JADESView_input_file.dat.zip)

**Comment by eclake** [comment]
Ah, looking more closely the only one with the wrong ID is the first object where it seems to have plotted the last object in the list first....

And looking through my other lists, it looks like that was the only one that it did it for - so maybe it was when I had a comment for the first object in the list...

**Comment by kevinhainline** [comment]
Let me take a look at replicating the bug, but this makes me feel better, since I didn't want you to lose a lot of work.

**Comment by kevinhainline** [comment]
Ok, I think that there's an issue when you hit the end of the list. If I go and create a new list using just the first five objects from class3_ids.list, and run JADESView, clicking "Quit" once I put in the notes on the final object (15261), I get this:

```
#ID    Notes
90    This is object 15261.
5137    This is object 5137.
6394    This is object 6394.
14017    This is object 14017.
15047    This is object 15047.
```

If I run this again, but click "next object" on reaching the final object (which just replots that object):

```
#ID    Notes
90    This is object 15261.
5137    This is object 5137.
6394    This is object 6394.
14017    This is object 14017.
15047    This is object 15047.
15261    This is object 15261.
```

I'm getting the same issue - there's an extra line at the beginning with the comment from the last object. I'm going to look into this weirdness today. I should maybe just quit the program when you get to the final object in your list and try to advance to the next object.

**Comment by eclake** [comment]
That would be a nice solution (quitting when you run into the last object) - and it's clearly not as big a deal as I initially feared as no information is actually lost (unless it's overwriting the first object?), just a spurious entry can show up at the beginning of a file.

**Comment by kevinhainline** [comment]
Ok! I think that I've pushed a fix to this. I tried to get it to quit out when you clicked "next object" on the final one in the list, but it wasn't saving the comment properly. So, instead, it acts as it should have all along, and if you click next object, it just stays on the same object. Let me know if you run into any other issues, because this is a pretty goofy way I've done this all.

**Comment by eclake** [comment]
Amazing, thank you Kevin!  Looks to be working again
